version: '3.8'

services:
  mcphub:
    image: samanhappy/mcphub:latest
    ports:
      - "3000:3000"
    volumes:
      # Mount the MCPHub configuration
      - ./mcphub-config.json:/app/mcp_settings.json
      # Mount the entire serena-dxt directory so MCPHub can access the server
      - .:/app/serena-dxt
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL for smart routing (if you want to use that feature)
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: mcphub
      POSTGRES_USER: mcphub
      POSTGRES_PASSWORD: mcphub_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:

