# Serena Project Configuration
# This file configures how Serena analyzes and works with your project

# Project metadata
name: "serena-gemini-workspace"
description: "Serena + Gemini CLI Integration Workspace"

# Project language and framework detection
language: "auto"  # auto-detect or specify: python, javascript, typescript, etc.

# File patterns to include/exclude
include_patterns:
  - "**/*.py"
  - "**/*.js"
  - "**/*.ts"
  - "**/*.jsx"
  - "**/*.tsx"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.toml"
  - "**/*.sh"

exclude_patterns:
  - "**/__pycache__/**"
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/.venv/**"
  - "**/venv/**"
  - "**/.env"
  - "**/dist/**"
  - "**/build/**"
  - "**/*.pyc"
  - "**/.DS_Store"

# Analysis settings
analysis:
  max_file_size: 1048576  # 1MB
  follow_symlinks: false
  
# Tool configurations
tools:
  enabled: true
  semantic_search: true
  code_analysis: true
  file_operations: true
