# Serena project configuration for Gemini CLI integration
language: python
ignore_all_files_in_gitignore: true
ignored_paths:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - ".git/**"
  - "*.log"
  - "__pycache__/**"
  - ".pytest_cache/**"
  - ".venv/**"
  - ".env"

# Enable all tools for maximum functionality
excluded_tools: []

# Project settings
read_only: false
project_name: "serena-gemini-integration"
initial_prompt: "This is a Serena + Gemini CLI integration project. Use Serena's tools for semantic code analysis, symbol navigation, and precise code editing."
